const afghanistanData = {
  Kabul: [
    "Bagrami",
    "Chahar Asyab",
    "Deh Sabz",
    "Farza",
    "Guldara",
    "Istalif",
    "Khak-e Jabbar",
    "Koh-e Daman",
    "Paghman",
    "Shakardara",
    "Surobi",
  ],
  Kandahar: [
    "Arghandab",
    "Arghistan",
    "Daman",
    "Ghorak",
    "Kandahar City",
    "Maruf",
    "Maywand",
    "Panjwayi",
    "Shah Wali Kot",
    "Spin Boldak",
    "Zhari",
  ],
  Herat: [
    "Adraskan",
    "Chesht-e Sharif",
    "Farsi",
    "Gulran",
    "Guzara",
    "Herat City",
    "Injil",
    "Karukh",
    "Kohsan",
    "Obe",
    "Pashtun Zarghun",
    "Shindand",
    "Zindajan",
  ],
  Balkh: [
    "Balkh",
    "Chahar Bolak",
    "Chimtal",
    "Dawlatabad",
    "Dehdadi",
    "Kaldar",
    "Khulm",
    "Mazar-i-Sharif",
    "Marmul",
    "Sholgara",
    "Shortepa",
    "Zari",
  ],
  Nangarhar: [
    "Achin",
    "Bati Kot",
    "Behsud",
    "Chaparhar",
    "Dara-i-Nur",
    "Deh Bala",
    "Dur Baba",
    "Ghani Khel",
    "Hisarak",
    "Jalalabad",
    "Kot",
    "Kuz Kunar",
    "Lal Pur",
    "Muhmand Dara",
    "Nazyan",
    "Pachir Aw Agam",
    "Rodat",
    "Sherzad",
    "Surkh Rod",
  ],
  Badakhshan: [
    "Argo",
    "Baharak",
    "Darayim",
    "Faizabad",
    "Ishkashim",
    "Jurm",
    "Khash",
    "Kishim",
    "Shahri Buzurg",
    "Wakhan",
    "Yamgan",
    "Zebak",
  ],
  Helmand: [
    "Baghran",
    "Dishu",
    "Garmser",
    "Kajaki",
    "Khanashin",
    "Lashkargah",
    "Musa Qala",
    "Nad Ali",
    "Nawa-I-Barakzai",
    "Sangin",
    "Washir",
  ],
  Ghazni: [
    "Ajristan",
    "Andar",
    "Deh Yak",
    "Gelan",
    "Ghazni City",
    "Giro",
    "Jaghori",
    "Khogyani",
    "Malistan",
    "Muqur",
    "Nawa",
    "Nawur",
    "Qarabagh",
    "Rashidan",
    "Waghaz",
  ],
  Kunduz: [
    "Aliabad",
    "Chahar Dara",
    "Dasht-e-Archi",
    "Imam Sahib",
    "Khan Abad",
    "Kunduz City",
    "Qalay-I-Zal",
  ],
  Parwan: [
    "Bagram",
    "Charikar",
    "Ghorband",
    "Jabal Saraj",
    "Salang",
    "Sheikh Ali",
    "Siyah Gird",
    "Surkhi Parsa",
  ],
  Baghlan: [
    "Andarab",
    "Baghlan-e Jadid",
    "Burka",
    "Dahana-i-Ghori",
    "Dushi",
    "Jalga",
    "Khinjan",
    "Nahrin",
    "Pul-i-Khumri",
    "Tala wa Barfak",
  ],
  Faryab: [
    "Almar",
    "Andkhoy",
    "Bala Murghab",
    "Dawlatabad",
    "Khani Chahar Bagh",
    "Khwaja Sabz Posh",
    "Maymana",
    "Pashtun Kot",
    "Qaramqol",
    "Qaysar",
    "Shirin Tagab",
  ],
  Logar: [
    "Baraki Barak",
    "Charkh",
    "Kharwar",
    "Khoshi",
    "Mohammad Agha",
    "Pul-i-Alam",
  ],
  Paktia: [
    "Ahmad Aba",
    "Chamkani",
    "Dand Wa Patan",
    "Gardez",
    "Jaji Aryob",
    "Shwak",
    "Zadran",
    "Zurmat",
  ],
  Wardak: [
    "Chak",
    "Day Mirdad",
    "Hesa Awal Behsood",
    "Hesa Duwum Behsood",
    "Jalrez",
    "Markazi Bihsud",
    "Maydan Shahr",
    "Nirkh",
    "Saydabad",
  ],
  Zabul: [
    "Arghandab",
    "Atghar",
    "Daychopan",
    "Kakar",
    "Mizan",
    "Qalat",
    "Shah Joy",
    "Shamulzayi",
    "Tarnak Wa Jaldak",
  ],
};

export default afghanistanData;
